services:
  app:
    build:
      context: .
      target: runner
    container_name: github-statistics-analog-js
    env_file:
      - .env
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - app_data:/app/.data
    restart: unless-stopped

volumes:
  app_data:
